---
title: "ch4_co2_analyses"
author: "Elizabeth Forbes"
format: html
editor: visual
---

## Manure Management and on-field Fertilizer Experiment (2025)

### Upload libraries:
```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(hms)
```


### Upload cleaned flux estimate data: CO2 and CH4

```{r}
all_flx <- read_xlsx("co2_n20_ch4_allflux2025.xlsx")

# add datetime in datetime format
all_flx <- all_flx %>% 
  mutate(DOY = floor(DOY_initial_value)) %>% 
  mutate(year = 2025,
         date = as.Date(paste0(year, "-01-01")) + (DOY-1)) %>% 
  # combine sept 10 and 11, and oct 14 and 15 (started and finished measurements on different days those two times due to weather/timing)
          mutate(
            date = case_when(
           date == "2025-09-10" ~ (date+days(1)),
           date == "2025-10-14" ~ (date+days(1)),
           TRUE ~ date)
         )

# add 'treatment' using case_when()
all_flx <- all_flx %>%
  mutate(treatment = case_when(
   plot_rep %in% c(2, 5, 7, 10, 15) ~ "control",
   plot_rep %in% c(1, 6, 11, 12, 13) ~ "slurry",
   plot_rep %in% c(3,4,8,9,14) ~ "compost"
  ))

# write_csv(all_flx, "test.csv", col_names = TRUE)
```


```{r}
# vegetation data:
biomass <- read_csv("vegetation_biomass.csv")

biomass$plot <- factor(biomass$plot, levels = c("Control", "Slurry", "Compost"))

```

### Initial data visualization: methane
```{r}
all_flx$treatment <- factor(all_flx$treatment, levels = c("control", "slurry", "compost"))

plot_data <- all_flx %>% 
  filter(FCH4_DRY < 1) %>%
  mutate(date = as.Date(date),
         date_index = as.numeric(factor(date)))

# Create a lookup table for date labels
date_labels <- plot_data %>% 
  distinct(date, date_index) %>% 
  arrange(date_index)

# add vertical line indicating fertilizer application date (May 28th, 2025)
app_date <- as.Date("2025-05-28")

# Create the plot
plot_data %>%
  ggplot(aes(x = date, 
             y = FCH4_DRY, 
             fill = treatment,
             group = interaction(date, treatment))) +
  geom_boxplot(outlier.size = 0.25,
               position = position_dodge(width = 2),  # increase dodge width
               width = 2) +  # set box width in days (adjust as needed)
  scale_x_date(date_breaks = "7 days", date_labels = "%b %d") +
  labs(x = "", 
       y = expression(paste("CH"[4], " soil flux, µmol m"^-2, "s"^-1)),
       title = "Methane fluxes through growing season") +
  geom_vline(xintercept = app_date, linetype = "dashed", color = "red") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 35, hjust = 1))

```
### carbon dioxide:
```{r}
plot_data <- all_flx %>% 
  filter(FCO2_DRY < 70) %>%
  mutate(date = as.Date(date),
         date_index = as.numeric(factor(date)))

# Create a lookup table for date labels
date_labels <- plot_data %>% 
  distinct(date, date_index) %>% 
  arrange(date_index)

# Create the plot
plot_data %>%
  ggplot(aes(x = date, 
             y = FCO2_DRY, 
             fill = treatment,
             group = interaction(date, treatment))) +
  geom_boxplot(outlier.size = 0.25,
               position = position_dodge(width = 2),  # increase dodge width
               width = 2) +  # set box width in days (adjust as needed)
  scale_x_date(date_breaks = "7 days", date_labels = "%b %d") +
  labs(x = "", 
       y = expression(paste("CO"[2], " soil flux, µmol m"^-2, "s"^-1)),
       title = "carbon dioxide fluxes through growing season") +
  geom_vline(xintercept = app_date, linetype = "dashed", color = "red") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 35, hjust = 1))
```

### nitrous oxide:
```{r}
plot_data <- all_flx %>% 
  # filter(FN2O < 70) %>%
  mutate(date = as.Date(date),
         date_index = as.numeric(factor(date)))

# Create a lookup table for date labels
date_labels <- plot_data %>% 
  distinct(date, date_index) %>% 
  arrange(date_index)

# Create the plot
plot_data %>%
  ggplot(aes(x = date, 
             y = log(FN2O), 
             fill = treatment,
             group = interaction(date, treatment))) +
  geom_boxplot(outlier.size = 0.25,
               position = position_dodge(width = 2),  # increase dodge width
               width = 2) +  # set box width in days (adjust as needed)
  scale_x_date(date_breaks = "7 days", date_labels = "%b %d") +
  labs(x = "", 
       y = expression(paste("N"[2],"O  soil flux, µmol m"^-2, "s"^-1, " (log transformed)")),
       title = "nitrous oxide fluxes through growing season") +
  geom_vline(xintercept = app_date, linetype = "dashed", color = "red") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 35, hjust = 1))
```


### end of season hay biomass:
```{r}
biomass %>% 
  ggplot(aes(x = plot, y = gdrymatt_per_m2, fill = plot))+
  geom_boxplot()+
  geom_jitter(alpha=0.5)+
  labs(x = "", y = "dry matter (g) per square meter")+
  theme_bw()
```


